add_rules("mode.debug", "mode.release")
add_repositories("liteldev-repo https://github.com/LiteLDev/xmake-repo.git")
add_requires("polyhook2", "libhat 7375873e560f46e8569c6a389c6077f4c7133089", "nlohmann_json", "fmt")
target("dll")
    set_options("type")
    set_languages("c++20")
    set_kind("shared")
    add_packages("polyhook2", "libhat", "nlohmann_json", "fmt")
    add_files("*.cpp")
    set_symbols("debug")